# Generated by Django 4.1.3 on 2022-12-20 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fechaDelPosteo']},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_articulos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='fechaDelEdit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='guia',
            field=models.SlugField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fechaDelPosteo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
