# Generated by Django 4.1.3 on 2022-12-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_articulo_options_remove_articulo_subtitulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='guia',
            new_name='slug',
        ),
    ]
