# Generated by Django 4.1.3 on 2022-12-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_guia_articulo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fechaDelComentario']},
        ),
    ]
