# Generated by Django 4.1.3 on 2022-12-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoDePerfil',
            field=models.ImageField(default='default.jpg', upload_to='Blog/fotosDePerfil'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='Blog/articuloImagenes/'),
        ),
    ]
