# Generated by Django 4.1.3 on 2022-12-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_usuario_nombre_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='Blog/media/articuloImagenes/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoDePerfil',
            field=models.ImageField(default='default.jpg', upload_to='Blog/media/fotosDePerfil'),
        ),
    ]
