# Generated by Django 4.1.3 on 2022-12-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_articulo_imagen_alter_usuario_fotodeperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
