# Generated by Django 4.1.3 on 2022-12-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
    ]
